### ISSUE TITLE
Please update this template registry

### ISSUE THREAD

**Issue by ledmonster** [aquaproj/template-private-aqua-registry#465]
The document [Create Private Registries](https://aquaproj.github.io/docs/develop-registry/create-private-registry) and this template registry are old comparing to [aqua-registry](https://github.com/aquaproj/aqua-registry) and its [documentation](https://aquaproj.github.io/docs/products/aqua-registry/contributing/).

Please update this template registry and related documentations.

For example, policy file needs to be added.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
We're considering archiving this repository because it's difficult to maintain this repository continuously.
Users can create private registries referring to the standard registry.

**Comment by ledmonster** [comment]
I see, thank you for your reply.
I think closing the repository is better than letting the repository old and referencing the repository from the official document.

On the other hand, do you welcome PR on this repository?
I have created a private registry and resolved some issues. So probably I can contribute to this repository this time. I can't keep contributing to the repository, though.

**Comment by suzuki-shunsuke** [comment]
If you have any comments, please create a discussion.

https://github.com/orgs/aquaproj/discussions
